image:
  file: Dockerfile
tasks:
  - command: |
      ln -s '/workspace/filius/filius bestanden' '/home/gitpod/filius bestanden'
      sleep 2
      ln -s '/workspace/filius/filius bestanden' '/home/gitpod/Desktop/filius bestanden'
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
